### ISSUE TITLE
Cannot combine OR|AND with NOT

### ISSUE THREAD

**Issue by djpate** [thoward/lucene-query-parser.js#11]
Hello,

I'm trying to parse the following query

```
foo:bar OR NOT baz:qux
```

I then  get the following output

```
{
   "left": {
      "field": "foo",
      "term": "bar",
      "similarity": null,
      "boost": null,
      "prefix": null
   },
   "operator": "OR",
   "right": {
      "field": "baz",
      "term": "qux",
      "similarity": null,
      "boost": null,
      "prefix": null
   }
}
```

As you can see the NOT gets lost. 

That might be the correct Lucene implementation but I'm not sure how to express that query then.

**Comment by whitelynx** [comment]
With the latest from npm (version 1.0.1) this seems to be an issue even without the `AND`/`OR`:

```
> parser.parse('NOT text:go');
{ left: { field: 'text', term: 'go' } }
> parser.parse('NOT go');
{ left: { field: '<implicit>', term: 'go' } }
```

It seems like `NOT` is always ignored.

**Comment by matthiasg** [comment]
@whitelynx  This library seems not longer supported. Though the case of `NOT text:go` isnt actually supported by lucene anyway see https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#NOT. A single field with NOT will always return an empty result, even though it might make sense syntactically

**Comment by thoward** [comment]
To give a more detailed answer, the query syntax only supports a single operator, so any conjunctions like this will drop everything but the first operator.

A reasonable library upgrade might be to detect situations these, and properly report on them with a error indicating invalid syntax (perhaps as an optional param to the library). Silently dropping portions of the user input is not ideal. I'll open a new ticket to capture that.
