### ISSUE TITLE
Please cut a new release that incorporate's parser changes

### ISSUE THREAD

**Issue by jamiehodge** [thoward/lucene-query-parser.js#14]
It would be great to have @bastien's parser changes available via npm.

**Comment by zuzusik** [comment]
This would be really great! 👍

**Comment by jamiehodge** [comment]
@thoward any update?

**Comment by thoward** [comment]
So sorry for letting this bitrot for so long folks. I'm cutting a new release today, after merging some recent contributions.

**Comment by thoward** [comment]
Released v1.1.0 today. Enjoy!
